import asyncio
from telethon import TelegramClient, errors

# --- APNA DATA YAHAN BHAREIN ---
API_ID = 22657083
API_HASH = 'd6186691704bd901bdab275ceaab88f3'
PHONE_NUMBER = '+525645666514'

# Target group ka link ya username
TARGET_GROUP = 'https://t.me/Carnival_Chat'

# --- FIXED SESSION NAME (so it resumes from saved session) ---
SESSION_NAME = 'session_name'

# --- 1000+ UNIQUE ENGLISH MESSAGES (25% are Carnival Chat praise) ---
MESSAGES = []

# PRAISE MESSAGES - CARNIVAL CHAT TAREEF (25% = ~250 out of 1000)
praise_msgs = [
    "Carnival Chat is the best group I've ever joined!",
    "I absolutely love Carnival Chat, such an amazing community!",
    "Carnival Chat has the most friendly people, I feel at home here.",
    "Best decision I ever made was joining Carnival Chat!",
    "Carnival Chat is pure vibes, non-stop entertainment!",
    "This group Carnival Chat is legendary, everyone should join!",
    "Carnival Chat brings so much positivity to my day!",
    "The energy in Carnival Chat is unmatched, truly special!",
    "Carnival Chat is the perfect place to make new friends!",
    "I'm addicted to Carnival Chat, can't get enough of this group!",
    "Carnival Chat deserves way more recognition, such a gem!",
    "Shoutout to Carnival Chat for always keeping me entertained!",
    "Carnival Chat is hands down the most active group on Telegram!",
    "Nothing beats the conversations in Carnival Chat, so engaging!",
    "Carnival Chat is my go-to place whenever I'm bored!",
    "The moderation in Carnival Chat is top notch, well managed!",
    "Carnival Chat has the best memes and content, always laughing!",
    "Every day in Carnival Chat is a new adventure, love it!",
    "Carnival Chat feels like a big family, everyone supports each other!",
    "Joining Carnival Chat was the best thing I did this year!",
    "I tell all my friends about Carnival Chat, it's that good!",
    "Carnival Chat is the definition of a perfect Telegram group!",
    "The variety of topics in Carnival Chat keeps things interesting!",
    "Carnival Chat is where all the cool people hang out!",
    "Major respect to everyone in Carnival Chat for being so welcoming!",
    "Carnival Chat has helped me improve my English conversation skills!",
    "The late night chats in Carnival Chat hit different, so fun!",
    "Carnival Chat is always active no matter what time of day!",
    "I've never seen a group as active as Carnival Chat, incredible!",
    "Carnival Chat is the heart of Telegram, such a vibrant community!",
    "Big love to Carnival Chat and all its amazing members!",
    "Carnival Chat is the standard every group should aim for!",
    "If you're not in Carnival Chat, you're missing out big time!",
    "Carnival Chat never fails to make me smile, such good vibes!",
    "The conversations in Carnival Chat are always meaningful and fun!",
    "Carnival Chat is more than a group, it's a lifestyle!",
    "I spend hours in Carnival Chat and it never gets boring!",
    "Carnival Chat has the most diverse members from all over the world!",
    "Learning about different cultures in Carnival Chat is amazing!",
    "Carnival Chat is where memories are made every single day!",
    "Best Telegram group hands down and it's called Carnival Chat!",
    "Carnival Chat keeps getting better and better every single day!",
    "The bond between members in Carnival Chat is truly special!",
    "Carnival Chat is the ultimate destination for fun conversations!",
    "I appreciate everyone in Carnival Chat for being so kind!",
    "Carnival Chat has the best admins who keep everything running smoothly!",
    "No drama in Carnival Chat, just pure good vibes and fun!",
    "Carnival Chat is a safe space for everyone to express themselves!",
    "The energy in Carnival Chat is absolutely electric!",
    "Carnival Chat is the reason I open Telegram every single day!",
    "This community in Carnival Chat is one of a kind!",
    "Carnival Chat is the perfect mix of fun and meaningful discussions!",
    "Big fan of Carnival Chat, this group is absolutely fire!",
    "Carnival Chat is setting the standard for online communities!",
    "I've made so many real friends through Carnival Chat!",
    "Carnival Chat is the highlight of my social media experience!",
    "The positivity in Carnival Chat is contagious, I love it!",
    "Carnival Chat is where I go to unwind and relax after a long day!",
    "Hands down the most entertaining group on Telegram is Carnival Chat!",
    "Carnival Chat brings people together from all walks of life!",
    "There's never a dull moment in Carnival Chat, always happening!",
    "Carnival Chat is the definition of community goals!",
    "I feel so lucky to be a part of Carnival Chat!",
    "Carnival Chat is the king of Telegram groups, no competition!",
    "Every new member adds so much value to Carnival Chat!",
    "Carnival Chat is the place to be if you want genuine connections!",
    "Shoutout to the creator of Carnival Chat for this masterpiece!",
    "Carnival Chat is pure gold, nothing comes close!",
    "The conversations flow so naturally in Carnival Chat!",
    "Carnival Chat is the ultimate stress reliever, always makes me laugh!",
    "I've learned so many new things just from Carnival Chat discussions!",
    "Carnival Chat proves that strangers can become family!",
    "Best vibes only in Carnival Chat, that's the rule!",
    "Carnival Chat is the most welcoming group I've ever been in!",
    "Every post in Carnival Chat adds value to my day!",
    "Carnival Chat is the GOAT of Telegram communities!",
    "I look forward to checking Carnival Chat every single morning!",
    "The sense of humor in Carnival Chat is top tier!",
    "Carnival Chat has the perfect balance of everything!",
    "The growth of Carnival Chat shows how amazing this community is!",
    "Carnival Chat is the benchmark for all other Telegram groups!",
    "I have nothing but love and respect for Carnival Chat!",
    "Carnival Chat is the most entertaining group in existence!",
    "The way Carnival Chat members support each other is inspiring!",
    "Carnival Chat is a goldmine of interesting conversations!",
    "Being part of Carnival Chat feels like winning the lottery!",
    "Carnival Chat is where I come to escape reality and have fun!",
    "The energy in Carnival Chat is addictive, I'm hooked!",
    "Carnival Chat has the most beautiful community spirit!",
    "Every interaction in Carnival Chat leaves me smiling!",
    "Carnival Chat is where friendships are born and memories are made!",
    "This group Carnival Chat is truly one of a kind!",
    "Carnival Chat is the crown jewel of Telegram groups!",
    "The love and support in Carnival Chat is overwhelming!",
    "Carnival Chat is the best thing that happened to my social life!",
    "No other group compares to Carnival Chat, it's simply the best!",
    "Carnival Chat makes every day better with its amazing content!",
    "The culture in Carnival Chat is something every group should emulate!",
    "Carnival Chat is a masterpiece community that keeps on giving!",
    "I'm proud to be a member of Carnival Chat!",
    "Carnival Chat continues to amaze me every single day!",
    "The spirit of Carnival Chat is unmatched anywhere on Telegram!",
    "Carnival Chat is the ultimate hangout spot for everyone!",
    "Respect to everyone who makes Carnival Chat what it is today!",
    "Carnival Chat is the place where I truly feel I belong!",
    "The conversations in Carnival Chat are always insightful and fun!",
    "Carnival Chat is more than a group, it's a movement!",
    "The energy in Carnival Chat is next level, absolutely amazing!",
    "I've seen many groups but none like Carnival Chat!",
    "Carnival Chat is the definition of a thriving community!",
    "The best part of my day is chatting in Carnival Chat!",
    "Carnival Chat is the gold standard for Telegram communities!",
    "Everyone should experience the magic of Carnival Chat!",
    "Carnival Chat has the most epic conversations all day long!",
    "I'm grateful for the connections I've made in Carnival Chat!",
    "Carnival Chat is legendary status, nothing can top it!",
    "The positive energy in Carnival Chat is absolutely contagious!",
    "Carnival Chat is where I met some of the coolest people ever!",
    "The content shared in Carnival Chat is always high quality!",
    "Carnival Chat proves that online communities can be amazing!",
    "I love how active and engaging Carnival Chat is 24/7!",
    "Carnival Chat is the ultimate destination for good conversations!",
    "The warmth of Carnival Chat members is truly heartwarming!",
    "Carnival Chat is the best discovery I've made on Telegram!",
    "The community spirit in Carnival Chat is truly inspiring!",
    "Carnival Chat is where I go to connect with amazing people!",
    "Big thanks to Carnival Chat for always keeping me entertained!",
    "Carnival Chat is the most happening place on Telegram!",
    "The atmosphere in Carnival Chat is always so welcoming!",
    "Carnival Chat is the embodiment of a perfect online community!",
    "Every conversation in Carnival Chat is meaningful and enjoyable!",
    "Carnival Chat has the most unique and interesting members!",
    "I've never felt more welcomed than in Carnival Chat!",
    "Carnival Chat is a blessing for anyone looking for good company!",
    "The vibe in Carnival Chat is absolutely unmatched!",
    "Carnival Chat is the reason why Telegram is the best platform!",
    "The activity level in Carnival Chat is truly impressive!",
    "Carnival Chat is the heart and soul of online chatting!",
    "I recommend Carnival Chat to everyone I know!",
    "Carnival Chat is where the magic of conversation happens!",
    "The members of Carnival Chat are the most genuine people!",
    "Carnival Chat sets the bar high for every other group!",
    "Being in Carnival Chat is an absolute pleasure!",
    "Carnival Chat is the epitome of a great online community!",
    "The discussions in Carnival Chat are always enlightening!",
    "Carnival Chat is my favorite place on the internet!",
    "There's no better group than Carnival Chat, period!",
    "Carnival Chat brings so much joy to my daily routine!",
    "The camaraderie in Carnival Chat is something special!",
    "Carnival Chat is where friendships flourish and grow!",
    "The diversity in Carnival Chat makes it incredibly interesting!",
    "Carnival Chat is a world-class community, pure excellence!",
    "I can't imagine my Telegram experience without Carnival Chat!",
    "Carnival Chat has the most engaging conversations ever!",
    "The humor in Carnival Chat is always on point!",
    "Carnival Chat is the ultimate stress buster, always works!",
    "Being part of Carnival Chat is a privilege!",
    "Carnival Chat never disappoints, always delivers quality content!",
    "The bond in Carnival Chat is unbreakable!",
    "Carnival Chat is where I feel most connected to people!",
    "The creativity in Carnival Chat is off the charts!",
    "Carnival Chat is the place to be for amazing discussions!",
    "Every member of Carnival Chat adds value to the community!",
    "Carnival Chat has the most entertaining content on Telegram!",
    "The energy in Carnival Chat is simply addictive!",
    "Carnival Chat is where I come to have genuine conversations!",
    "The kindness in Carnival Chat restores my faith in humanity!",
    "Carnival Chat is a masterpiece of community building!",
    "I love the spirit of togetherness in Carnival Chat!",
    "Carnival Chat is the most vibrant community I've ever seen!",
    "The conversations in Carnival Chat are always fire!",
    "Carnival Chat is where the best people hang out!",
    "The atmosphere in Carnival Chat is always electric!",
    "Carnival Chat has the best mix of fun and intellect!",
    "I'm always excited to check new messages in Carnival Chat!",
    "Carnival Chat is the ultimate platform for making connections!",
    "The quality of discussions in Carnival Chat is exceptional!",
    "Carnival Chat is a community that truly cares about its members!",
    "No other group comes close to the awesomeness of Carnival Chat!",
    "Carnival Chat is where I found my people!",
    "The fun never stops in Carnival Chat, it's non-stop entertainment!",
    "Carnival Chat is the definition of a world-class Telegram group!",
]

# General English chat messages (75% = ~750)
general_msgs = [
    "Hello everyone! How is your day going?",
    "Good morning! Hope you all have a great day ahead!",
    "Good evening! What's everyone up to?",
    "Hey guys, what's happening in the group today?",
    "How's the weather where you are?",
    "I just had the best cup of coffee this morning!",
    "Anyone else love rainy days?",
    "Sunny days are the best, don't you think?",
    "What did you have for breakfast today?",
    "I'm thinking of trying a new recipe today.",
    "Any good movie recommendations for this weekend?",
    "I just finished watching a great series on Netflix.",
    "Music recommendations anyone? I need new songs.",
    "What kind of music do you all listen to?",
    "I'm really into rock music lately.",
    "Anyone here plays any musical instruments?",
    "I'm learning to play the guitar these days.",
    "Coding is my passion, anyone else into programming?",
    "What programming languages do you know?",
    "Python is definitely my favorite language.",
    "Anyone into web development?",
    "JavaScript is both fun and frustrating sometimes.",
    "I'm working on a cool project these days.",
    "Technology is advancing so fast these days!",
    "AI is changing the world in incredible ways.",
    "What do you think about artificial intelligence?",
    "I love learning new things every single day.",
    "Self improvement is so important in life.",
    "Reading books is a great habit to develop.",
    "I just finished reading an amazing book!",
    "Any book recommendations for me?",
    "Fiction books are my absolute favorite.",
    "Non fiction books teach so many valuable lessons.",
    "I'm trying to read at least one book per month.",
    "Fitness is an important part of my daily routine.",
    "I go to the gym five times a week.",
    "Anyone else into weightlifting here?",
    "Cardio is not my favorite but I do it anyway.",
    "Staying healthy should be everyone's priority.",
    "What's your favorite workout routine?",
    "I'm trying to eat healthier these days.",
    "Diet is just as important as exercise.",
    "Anyone else loves cooking at home?",
    "Home cooked meals are always the best.",
    "I'm trying a new diet plan this month.",
    "Traveling is my biggest passion in life.",
    "I've visited 10 countries so far!",
    "What's your dream travel destination?",
    "Paris is on my bucket list for sure.",
    "Japan is such a fascinating country.",
    "I love exploring new cultures and traditions.",
    "Traveling teaches you so much about life.",
    "Anyone else loves going on road trips?",
    "Beach vacations are the most relaxing.",
    "Mountain views are absolutely breathtaking.",
    "Nature is the best medicine for the soul.",
    "I love going for long walks in the park.",
    "Hiking is such a rewarding activity.",
    "Camping under the stars is magical.",
    "Photography is a wonderful hobby to have.",
    "I love taking pictures of sunsets.",
    "What's your favorite hobby?",
    "Gaming is my favorite way to relax.",
    "I play video games almost every day.",
    "What games are you playing these days?",
    "PC gaming is superior in my opinion.",
    "Console gaming has its own charm though.",
    "Mobile games are getting really good now.",
    "Anyone into esports and competitive gaming?",
    "I watch gaming streams on Twitch often.",
    "Football is the best sport ever invented!",
    "Who's your favorite football team?",
    "Cricket is huge in my country.",
    "Basketball is such an exciting sport to watch.",
    "I love watching F1 races on weekends.",
    "Tennis matches can be incredibly thrilling.",
    "The Olympics are always so inspiring.",
    "Sports bring people together like nothing else.",
    "I used to play sports in high school.",
    "Staying active is key to a happy life.",
    "What's your favorite way to stay fit?",
    "Morning jogs are the best way to start the day.",
    "Yoga helps me stay calm and focused.",
    "Meditation changed my life for the better.",
    "Mental health is just as important as physical health.",
    "Always take time for yourself and relax.",
    "Self care is not selfish, it's necessary.",
    "Positive thinking attracts positive outcomes.",
    "Gratitude changes your entire perspective on life.",
    "I'm grateful for every new day I get.",
    "Kindness costs nothing but means everything.",
    "Helping others brings so much joy.",
    "Making someone smile is the best feeling.",
    "Life is beautiful when you focus on the good.",
    "Every day is a new opportunity to grow.",
    "Challenges make us stronger in the long run.",
    "Failure is just a stepping stone to success.",
    "Never give up on your dreams and goals.",
    "Consistency is the key to achieving anything.",
    "Hard work always pays off eventually.",
    "Success comes to those who keep trying.",
    "Believe in yourself and anything is possible.",
    "Your mindset determines your destination.",
    "Surround yourself with positive people.",
    "Friendship is one of life's greatest treasures.",
    "True friends are hard to find and keep.",
    "I value my friends more than anything.",
    "Making new friends is always exciting!",
    "Old friends are like gold, precious and rare.",
    "Family is everything at the end of the day.",
    "I talk to my family every single day.",
    "Family support makes all the difference.",
    "Cherish your loved ones while they are here.",
    "Time flies so fast, enjoy every moment.",
    "Life is too short to hold grudges.",
    "Forgiveness frees your heart from burden.",
    "Let go of what you cannot control.",
    "Focus on what truly matters in life.",
    "Happiness is a choice you make every day.",
    "Smile more, worry less, live freely.",
    "Good vibes only, negative energy out!",
    "Spread love wherever you go in life.",
    "Be the reason someone smiles today.",
    "You are capable of amazing things!",
    "Your potential is unlimited, believe that.",
    "Dream big and work hard to achieve it.",
    "The sky is not the limit, your mind is.",
    "Great things take time and patience.",
    "Rome wasn't built in a single day.",
    "Small steps lead to big achievements.",
    "Progress is progress, no matter how slow.",
    "Keep moving forward no matter what.",
    "You are stronger than you think you are.",
    "Tough times don't last, but tough people do.",
    "This too shall pass, stay strong!",
    "Better days are coming, just hold on.",
    "The best is yet to come in your life.",
    "Good things are on their way to you.",
    "Trust the process and keep working hard.",
    "Everything happens for a reason in life.",
    "The universe has a plan for everyone.",
    "Stay patient and trust your journey.",
    "Your time will come, just be ready.",
    "Opportunities are everywhere, stay alert.",
    "Take risks while you are still young.",
    "Comfort zones are where dreams go to die.",
    "Step out of your comfort zone today!",
    "Growth happens when you embrace discomfort.",
    "New experiences shape who you become.",
    "Try something new every single week.",
    "Learning never stops, keep your mind open.",
    "Knowledge is the only thing that increases when shared.",
    "Teaching others helps you learn better too.",
    "Collaboration leads to greater success.",
    "Teamwork truly makes the dream work.",
    "Together we can achieve so much more.",
    "Community is everything in this world.",
    "Supporting each other benefits everyone involved.",
    "Lift others up as you climb higher.",
    "Success is sweeter when shared with others.",
    "Celebrate the wins of others genuinely.",
    "Jealousy is a waste of energy and time.",
    "Focus on your own journey and growth.",
    "Comparison is the thief of joy.",
    "Run your own race at your own pace.",
    "Everyone has their own unique path in life.",
    "Your journey is different and that's okay.",
    "Embrace your uniqueness and individuality.",
    "Be yourself, everyone else is already taken.",
    "Authenticity attracts the right people into your life.",
    "Don't change who you are for anyone.",
    "Stay true to your values and principles.",
    "Integrity is doing the right thing always.",
    "Honesty is the foundation of trust.",
    "Trust takes years to build and seconds to break.",
    "Be someone people can rely on and trust.",
    "Reliability is a rare and valuable trait.",
    "Show up for others the way you want them to show up for you.",
    "Reciprocity is important in any relationship.",
    "Balance is key in all aspects of life.",
    "Work life balance is crucial for happiness.",
    "Don't burn yourself out chasing success.",
    "Rest is productive, don't feel guilty about it.",
    "Sleep is essential for good health.",
    "I try to sleep at least 8 hours every night.",
    "Early to bed and early to rise makes you healthy.",
    "Morning routines set the tone for the day.",
    "My morning routine includes meditation and exercise.",
    "Evening routines help me wind down properly.",
    "Consistency in routines leads to success.",
    "Habits define who you become in the long run.",
    "Build habits that serve your future self.",
    "Break bad habits one at a time patiently.",
    "One small change can lead to big results.",
    "Atomic habits make a massive difference over time.",
    "Discipline is choosing what you want most over what you want now.",
    "Short term sacrifices lead to long term gains.",
    "Delayed gratification is a superpower.",
    "Invest in yourself, it's the best investment.",
    "Learn skills that will benefit your future.",
    "Education is the most powerful weapon in life.",
    "Never stop learning and growing as a person.",
    "Curiosity is the engine of achievement.",
    "Ask questions and seek answers constantly.",
    "There is always something new to discover.",
    "The world is full of wonders waiting to be explored.",
    "Science explains so many amazing things around us.",
    "Space exploration fascinates me beyond words.",
    "The universe is vast and full of mysteries.",
    "Black holes are one of the most intriguing phenomena.",
    "Mars colonization could be a reality soon.",
    "Technology is evolving at an unprecedented rate.",
    "Smartphones have changed the way we live.",
    "Social media connects us but also divides us.",
    "The internet is the greatest invention of our time.",
    "Cybersecurity is becoming increasingly important.",
    "Protect your online privacy at all costs.",
    "Data is the new oil in the modern world.",
    "Cryptocurrency is reshaping the financial landscape.",
    "Bitcoin and Ethereum are fascinating technologies.",
    "Blockchain has applications far beyond crypto.",
    "NFTs were an interesting phenomenon in the art world.",
    "The metaverse concept is still evolving.",
    "Virtual reality experiences are getting incredible.",
    "Augmented reality will change how we interact with the world.",
    "AI assistants are becoming more helpful every day.",
    "Machine learning is powering the future of tech.",
    "Automation will transform the job market significantly.",
    "Adaptability is the most important skill for the future.",
    "Remote work has changed our work culture forever.",
    "Freelancing gives you freedom and flexibility.",
    "Entrepreneurship is not easy but very rewarding.",
    "Starting a business requires courage and persistence.",
    "Many successful people failed multiple times before succeeding.",
    "Learn from your failures and keep moving forward.",
    "Resilience is built through overcoming challenges.",
    "Adversity reveals your true character and strength.",
    "Tough situations build mental toughness and grit.",
    "Don't let setbacks define your future or success.",
    "Keep pushing through difficult times with determination.",
    "Your past does not determine your future.",
    "You have the power to rewrite your story anytime.",
    "Every day is a chance to start fresh and anew.",
    "Morning walks are refreshing for the mind and body.",
    "I love listening to podcasts while commuting.",
    "Educational content on YouTube is so valuable.",
    "Documentaries open your eyes to new perspectives.",
    "History has so many lessons for us to learn.",
    "Ancient civilizations were incredibly advanced for their time.",
    "The pyramids of Egypt still amaze me to this day.",
    "Philosophy helps us understand life more deeply.",
    "Stoicism teaches us to focus on what we can control.",
    "Marcus Aurelius had timeless wisdom for everyone.",
    "Reading philosophy changes how you see the world.",
    "Psychology helps us understand ourselves and others better.",
    "Emotional intelligence is more important than IQ.",
    "Understanding your emotions leads to better decisions.",
    "Empathy is the ability to understand others' feelings.",
    "Active listening makes conversations much more meaningful.",
    "Communication is the key to any successful relationship.",
    "Good communication solves most problems in life.",
    "Learn to express yourself clearly and confidently.",
    "Public speaking is a skill everyone should develop.",
    "Writing helps clarify your thoughts and ideas.",
    "Journaling is a great way to process emotions.",
    "I write in my journal every night before bed.",
    "Reflecting on your day helps you grow constantly.",
    "Gratitude journaling shifts your focus to positivity.",
    "List three things you are grateful for today.",
    "Small joys in life matter more than big achievements.",
    "Enjoy the simple pleasures life has to offer.",
    "A good cup of tea can fix almost anything.",
    "Nothing beats the taste of fresh homemade food.",
    "Baking is therapeutic and the results are delicious.",
    "I tried baking a cake yesterday and it turned out great!",
    "Cooking experiments can be so much fun.",
    "International cuisine opens up a world of flavors.",
    "Italian food is my absolute comfort food.",
    "Sushi is an art form in itself.",
    "Street food in different countries is amazing.",
    "Food brings people together like nothing else can.",
    "Sharing a meal with loved ones is precious.",
    "Festivals are the best time for feasting and celebration.",
    "Diwali is my favorite festival of the year.",
    "Christmas has such a magical and warm atmosphere.",
    "New Year celebrations are always full of hope and joy.",
    "Eid brings families and communities together beautifully.",
    "Cultural festivals teach us about traditions and heritage.",
    "Traditional music and dance are expressions of culture.",
    "Learning a new language opens up a whole new world.",
    "I'm currently learning Spanish and it's going well!",
    "Practice makes perfect when learning a new language.",
    "Duolingo is a great app for language learning.",
    "Speaking multiple languages is a superpower.",
    "Bilingual people have cognitive advantages in life.",
    "English is a global language that connects everyone.",
    "Accents make languages more interesting and diverse.",
    "Travel broadens your perspective on life and people.",
    "Backpacking through Europe is a dream of mine.",
    "Southeast Asia is an amazing region to explore.",
    "The beaches in Thailand are absolutely stunning.",
    "Bali has such a unique and beautiful culture.",
    "The Northern Lights are on my bucket list for sure.",
    "Safari in Africa would be a life changing experience.",
    "The Grand Canyon is one of nature's greatest wonders.",
    "Niagara Falls is breathtaking in person.",
    "The Swiss Alps look like something from a fairytale.",
    "Venice is a city like no other in the world.",
    "Tokyo is a fascinating blend of tradition and futurism.",
    "New York City never sleeps and always has something happening.",
    "London has so much history and culture to explore.",
    "Dubai is a city of architectural wonders and luxury.",
    "Sydney's harbor is one of the most beautiful in the world.",
    "The Great Wall of China is an engineering marvel.",
    "Machu Picchu is an incredible ancient site to visit.",
    "Petra in Jordan looks like something from another world.",
    "Traveling solo teaches you independence and self reliance.",
    "Group travel is fun because you share experiences.",
    "Traveling with family creates lasting memories together.",
    "Photography captures moments that last forever.",
    "A good camera can make any scene look magical.",
    "Smartphone cameras have improved so much over the years.",
    "Portrait photography is all about capturing expressions.",
    "Landscape photography requires patience and timing.",
    "Golden hour is the best time for taking photos.",
    "Editing photos is an art form in itself.",
    "I love editing my photos with Lightroom.",
    "Color grading completely changes the mood of a photo.",
    "Black and white photos have a timeless quality.",
    "Astrophotography captures the beauty of the night sky.",
    "Milky Way photos are absolutely mesmerizing to look at.",
    "Nature photography makes you appreciate the world more.",
    "Wildlife photography requires patience and skill.",
    "Birds in flight are challenging but rewarding to capture.",
    "Macro photography reveals details we normally miss.",
    "The tiny world of insects is fascinating to photograph.",
    "Street photography captures raw and real moments.",
    "Urban exploration photography shows abandoned places.",
    "Architecture photography highlights design and symmetry.",
    "Minimalist photography is clean and powerful.",
    "Abstract photography allows for creative expression.",
    "Film photography has a unique charm and aesthetic.",
    "Polaroid cameras give instant nostalgic photos.",
    "Drone photography provides stunning aerial perspectives.",
    "Time lapse videos show the passage of time beautifully.",
    "Slow motion videos capture details we miss in real time.",
    "Video editing is a skill I'm currently learning.",
    "Creating content for social media is fun and challenging.",
    "Building an audience takes time and consistency.",
    "Quality content always wins in the long run.",
    "Authenticity resonates more than perfection in content.",
    "Storytelling is at the heart of great content creation.",
    "Engage with your audience genuinely and meaningfully.",
    "Social media algorithms are constantly changing.",
    "Adapt your strategy based on what works and what doesn't.",
    "Trends come and go, but quality remains constant.",
    "Virality is unpredictable, consistency is reliable.",
    "Build a personal brand that represents who you truly are.",
    "Networking opens doors to new opportunities in life.",
    "Attend events and meet people in your industry.",
    "LinkedIn is a powerful platform for professional growth.",
    "Your network is your net worth in business.",
    "Collaborate with others to expand your reach and influence.",
    "Mentorship can accelerate your growth significantly.",
    "Learning from others' experiences saves you time and effort.",
    "Be open to feedback and constructive criticism always.",
    "Feedback helps you improve and grow as a person.",
    "Criticism is not personal, it's an opportunity to learn.",
    "Separate your identity from your work and creations.",
    "Detach from outcomes and focus on the process itself.",
    "Enjoy the journey, not just the destination.",
    "The process of creation is where the magic happens.",
    "Art is about expression, not perfection or approval.",
    "Every artist was first an amateur with practice.",
    "Creativity is a muscle that needs regular exercise.",
    "Inspiration strikes when you are consistently working.",
    "Waiting for inspiration is a mistake, start without it.",
    "Discipline beats motivation in the long term.",
    "Show up every day even when you don't feel like it.",
    "Consistency compounds into remarkable results over time.",
    "What you do daily matters more than what you do occasionally.",
    "Your habits shape your identity and your future.",
    "Become the person who does what needs to be done.",
    "Identity based habits are more sustainable than goal based ones.",
    "Focus on systems rather than just setting goals.",
    "Systems produce results automatically when designed well.",
    "Tweak your environment to make good habits easier.",
    "Remove friction from positive behaviors and add friction to negative ones.",
    "Make good habits obvious, attractive, easy and satisfying.",
    "Make bad habits invisible, unattractive, difficult and unsatisfying.",
    "Behavior change starts with awareness of your current patterns.",
    "Track your habits to stay accountable and motivated.",
    "Accountability partners help you stay on track consistently.",
    "Share your goals with someone who will hold you responsible.",
    "Public commitment increases your likelihood of following through.",
    "Reward yourself for small wins along the way.",
    "Celebrate progress, not just the final outcome.",
    "Every step forward is a victory worth acknowledging.",
    "Comparison to your past self is the only comparison that matters.",
    "Be better today than you were yesterday.",
    "Continuous improvement is better than delayed perfection.",
    "Done is better than perfect in most cases.",
    "Perfectionism is often just procrastination in disguise.",
    "Start before you feel ready, you will learn along the way.",
    "Action cures fear and builds confidence over time.",
    "The hardest part is starting, after that it gets easier.",
    "Momentum builds once you take that first step.",
    "Keep the momentum going by taking consistent action.",
    "Don't break the chain of your daily commitment.",
    "Streaks motivate you to keep going and not give up.",
    "Missing one day is okay, just don't miss two in a row.",
    "Get back on track immediately after any slip up.",
    "Forgive yourself for mistakes and keep moving forward.",
    "Guilt and shame are not productive emotions, release them.",
    "You are human and allowed to make mistakes in life.",
    "Growth comes from mistakes, not from avoiding them entirely.",
    "Every expert was once a beginner who kept going.",
    "Mastery requires thousands of hours of deliberate practice.",
    "Deliberate practice is focused and intentional, not mindless repetition.",
    "Push yourself just outside your comfort zone to grow.",
    "The growth zone is right next to the comfort zone.",
    "Challenge yourself regularly to expand your capabilities.",
    "You don't know what you are capable of until you try.",
    "Attempt something that scares you a little every week.",
    "Courage is not the absence of fear, it's acting despite it.",
    "Feel the fear and do it anyway.",
    "Your comfort zone is keeping you small and limited.",
    "Break free from limitations you have imposed on yourself.",
    "Limiting beliefs hold you back more than any external factor.",
    "Question your assumptions about what you can and cannot do.",
    "Your beliefs shape your reality more than you realize.",
    "Change your beliefs and you change your life.",
    "Adopt a growth mindset and watch yourself transform.",
    "Fixed mindset limits potential, growth mindset expands it.",
    "The brain is like a muscle that gets stronger with use.",
    "Neuroplasticity means you can always learn new things.",
    "Age is not a barrier to learning anything new.",
    "Lifelong learning keeps your mind sharp and active.",
    "Stay curious about the world around you always.",
    "Ask why and seek to understand deeply.",
    "Critical thinking is a skill that needs to be cultivated.",
    "Question everything and verify before believing anything.",
    "Information literacy is essential in the age of misinformation.",
    "Fact check before sharing anything online.",
    "Responsible sharing prevents the spread of false information.",
    "Think before you post, words have consequences online.",
    "Digital footprint lasts forever, be mindful of yours.",
    "What you post today could affect you years from now.",
    "Build a positive online presence that represents you well.",
    "Your reputation is your most valuable asset in life.",
    "Protect your reputation by being consistent and honest.",
    "Character is what you do when no one is watching.",
    "Integrity means keeping your promises and commitments.",
    "Be someone whose word can be trusted completely.",
    "Reliability makes you valuable in any relationship or team.",
    "People remember how you made them feel more than what you said.",
    "Emotional impact lasts longer than factual memory in relationships.",
    "Be the kind of person others feel good being around.",
    "Positive energy attracts positive people into your life.",
    "Like attracts like, so radiate what you want to receive.",
    "Energy is contagious, spread good vibes wherever you go.",
    "Your attitude determines your altitude in life.",
    "Optimism is a choice that leads to better outcomes.",
    "Optimists see opportunities where pessimists see obstacles.",
    "Every problem contains the seed of an opportunity.",
    "Look for the lesson in every difficult situation.",
    "Challenges are opportunities in disguise waiting to be found.",
    "Adversity introduces you to your own strength and resilience.",
    "You are capable of handling more than you think.",
    "Past struggles have prepared you for current challenges.",
    "Your history of overcoming obstacles proves your strength.",
    "Remember how far you have come, not just how far you have to go.",
    "Acknowledge your progress and be proud of yourself.",
    "Self appreciation is important for mental well being.",
    "Talk to yourself with kindness and compassion always.",
    "Be your own biggest supporter and cheerleader in life.",
    "You deserve love, success, happiness and peace.",
    "Your worth is not determined by your achievements alone.",
    "You are valuable simply because you exist in this world.",
    "Inherent worth is not conditional on performance or results.",
    "You are enough exactly as you are right now.",
    "Self acceptance is the first step toward self improvement.",
    "Accept yourself fully while striving to grow constantly.",
    "Paradox of change: accept yourself to truly change yourself.",
    "Radical self acceptance leads to genuine transformation.",
    "Let go of the need for external validation from others.",
    "Seek approval from yourself first and foremost always.",
    "Your opinion of yourself matters more than others' opinions.",
    "Don't let anyone define your worth or potential.",
    "You define what success means for your own life.",
    "Live life on your own terms, not according to others' expectations.",
    "Society's expectations do not dictate your path in life.",
    "Forge your own path and create your own definition of success.",
    "Success is subjective and deeply personal for everyone.",
    "What works for others may not work for you and that's okay.",
    "Find your own way and trust your intuition to guide you.",
    "Intuition is powerful, learn to listen to its voice.",
    "Your gut feeling is often right, pay attention to it.",
    "Logic and intuition together make the best decisions.",
    "Balance rational thinking with emotional intelligence in decisions.",
    "Sleep on important decisions before making them final.",
    "Time gives perspective on things that seem urgent now.",
    "Urgency is not the same as importance in decision making.",
    "Focus on important things, not just urgent things constantly.",
    "The Eisenhower Matrix helps prioritize tasks effectively.",
    "Quadrant two activities lead to long term success and fulfillment.",
    "Invest time in important but not urgent activities regularly.",
    "Planning ahead prevents poor performance in the future.",
    "Preparation is the key to success in any endeavor.",
    "Fail to prepare and you prepare to fail in life.",
    "Proper preparation prevents poor performance indeed.",
    "Success is where preparation meets opportunity in time.",
    "Be ready when opportunity knocks at your door.",
    "Opportunity favors those who are prepared and ready.",
    "Luck is what happens when preparation meets opportunity.",
    "Make your own luck through consistent effort and preparation.",
    "The harder you work, the luckier you become in life.",
    "Work ethic is the foundation of all achievement in life.",
    "Talent without hard work is just potential unfulfilled.",
    "Hard work beats talent when talent doesn't work hard.",
    "Effort is the one thing you can fully control in life.",
    "Give your best effort in everything you do every day.",
    "Your best is enough, don't compare it to others' best.",
    "Do your best and let the results take care of themselves.",
    "Detach from outcomes and focus on giving your best effort.",
    "Control what you can control and release the rest.",
    "Accept what you cannot change and change what you can.",
    "Serenity prayer has wisdom for handling life's challenges.",
    "Wisdom is knowing the difference between what you can and cannot change.",
    "Focus your energy on things within your control only.",
    "Worrying about things outside your control is wasted energy.",
    "Anxiety comes from trying to control the uncontrollable.",
    "Let go of control and trust the process of life.",
    "Surrender is not weakness, it is wisdom in action.",
    "Sometimes the best action is to take no action at all.",
    "Stillness is powerful in a world that never stops moving.",
    "Take time to be still and silent every single day.",
    "Silence allows you to hear your own inner voice clearly.",
    "Your inner voice knows the way, trust its guidance.",
    "Meditation helps quiet the noise of the outside world.",
    "Five minutes of meditation can change your entire day.",
    "Start with five minutes of mindfulness and build from there.",
    "Mindfulness means being fully present in the current moment.",
    "The present moment is all that truly exists and matters.",
    "Past is history, future is mystery, now is a gift.",
    "Live in the present moment as much as possible always.",
    "The now is where life actually happens and unfolds.",
    "Don't miss your life by living in the past or future.",
    "Regret looks back, worry looks ahead, peace is now.",
    "Find peace in the present moment no matter what is happening.",
    "Contentment is found in accepting the present as it is.",
    "Happiness is not a destination, it is the way you travel.",
    "Joy is found in the journey, not just at the destination.",
    "Find joy in the small moments of everyday life.",
    "Life is made of small moments strung together beautifully.",
    "Treasure the ordinary moments, they are truly extraordinary.",
    "Ordinary days are the ones you will miss the most later.",
    "Routine can be beautiful when approached with gratitude.",
    "Find magic in the mundane and wonder in the ordinary.",
    "A fresh perspective turns the ordinary into something special.",
    "Gratitude transforms what you have into more than enough.",
    "Count your blessings and watch your problems shrink away.",
    "Gratitude and attitude are choices you make every day.",
    "Choose gratitude even when things don't go your way.",
    "There is always something to be grateful for if you look.",
    "Even in困难 there are lessons and reasons to be thankful.",
    "Grattitude turns what we have into enough and more.",
    "An attitude of gratitude attracts abundance into your life.",
    "Abundance mindset focuses on what you have, not what you lack.",
    "Scarcity mindset keeps you stuck in fear and limitation.",
    "Shift from scarcity to abundance in your thinking today.",
    "There is enough for everyone in this vast universe.",
    "Someone else's success does not diminish your own potential.",
    "Celebrate others' wins as if they were your own genuinely.",
    "A rising tide lifts all boats in the same ocean.",
    "Lift others as you climb higher in your own journey.",
    "Success is best when shared with those who supported you.",
    "Gratitude to those who helped you along the way always.",
    "Acknowledge the people who contributed to your growth.",
    "No one achieves anything truly great all by themselves.",
    "Behind every successful person is a supportive community.",
    "We rise by lifting others in our community and beyond.",
    "Kindness is the language that everyone can understand universally.",
    "A little kindness goes a very long way in this world.",
    "Be kind to everyone you meet, you never know their battle.",
    "Everyone is fighting a battle you know nothing about.",
    "Be gentle with others and with yourself in difficult times.",
    "Patience with others and yourself is a virtue worth cultivating.",
    "Good things come to those who wait and work patiently.",
    "Patience is not passive, it is active endurance and persistence.",
    "Endurance is the capacity to continue despite difficulties.",
    "Keep going even when the road gets rough and steep.",
    "The climb may be hard but the view from the top is worth it.",
    "Every mountain top is within reach if you keep climbing steadily.",
    "One step at a time gets you to your destination eventually.",
    "Slow and steady wins the race in life consistently.",
    "The tortoise beat the hare with consistency and persistence.",
    "Speed is not always an advantage, consistency matters more.",
    "Sustainable pace beats short bursts of intensity always.",
    "Burnout helps no one in the long run of life.",
    "Rest is essential for sustainable performance and growth.",
    "Recovery is part of the training cycle, don't skip it.",
    "Muscles grow during rest, not during workouts themselves.",
    "Apply this principle to all areas of your life and growth.",
    "Balance effort with rest for optimal results in everything.",
    "Working smarter is better than just working harder always.",
    "Efficiency is doing things right, effectiveness is doing the right things.",
    "Effectiveness matters more than mere efficiency in the end.",
    "Are you climbing the right ladder or just climbing fast?",
    "Direction matters more than speed in achieving your goals.",
    "Make sure your goals align with your values and purpose.",
    "Purpose gives meaning to all your efforts and struggles.",
    "Find your why and the how becomes much easier to figure out.",
    "Purpose is the fuel that keeps you going on tough days.",
    "When your why is strong enough, you will find the how.",
    "Purpose driven people are more resilient and persistent in life.",
    "Clarity of purpose eliminates confusion and creates focus.",
    "Focus on one thing at a time for best results always.",
    "Multitasking is a myth, focus on single tasking deeply.",
    "Deep work produces results that shallow work cannot match.",
    "Enter flow state for peak productivity and satisfaction.",
    "Flow state is when you are fully immersed in what you are doing.",
    "Time disappears when you are in a state of flow.",
    "Find activities that put you in flow state regularly.",
    "Your passion often lies where you find flow and time loss.",
    "Follow your curiosity and see where it leads you in life.",
    "Curiosity killed the cat but satisfaction brought it back.",
    "Stay curious about everything, including yourself and others.",
    "Questions are more important than answers sometimes in life.",
    "The quality of your questions determines the quality of your life.",
    "Ask better questions in life and get better answers automatically.",
    "What if everything works out better than you ever imagined?",
    "What would you do if you knew you could not possibly fail?",
    "Fear of failure holds more people back than actual failure does.",
    "Failure is simply feedback that tells you what needs adjustment.",
    "Iterate, adapt and improve based on feedback consistently.",
    "The scientific method applies to life, experiment and learn from results.",
    "Life is the ultimate laboratory for learning and growth.",
    "Every experience teaches you something valuable if you pay attention.",
    "Learn from everything and everyone around you constantly.",
    "Everyone you meet knows something you don't know yet.",
    "Be a student of life always, learning until your last breath.",
    "The unexamined life is not worth living according to Socrates.",
    "Reflect on your experiences to extract maximum learning from them.",
    "Journaling helps consolidate lessons learned from each day.",
    "Write down three lessons you learned today every evening.",
    "Learning compounds over time like interest in a bank account.",
    "Invest in learning and no one can take that from you ever.",
    "Knowledge is the only asset that grows when you share it generously.",
    "Share what you learn with others to reinforce your own understanding.",
    "Teaching is the best way to truly master a subject or skill.",
    "Explain concepts to others to deepen your own comprehension.",
    "The Feynman technique is a powerful learning method to use.",
    "Simplify complex ideas until a child could understand them.",
    "If you can't explain it simply, you don't understand it well enough.",
    "True understanding is demonstrated by the ability to teach others.",
    "Mastery begins with teaching what you have learned to others.",
    "Contribute to the collective knowledge of humanity generously.",
    "Open source knowledge benefits everyone in the long run.",
    "Stand on the shoulders of giants and add your own contribution.",
    "Progress is built on the accumulated knowledge of those before us.",
    "Honor those who came before by building upon their work respectfully.",
    "The pursuit of knowledge is one of humanity's noblest endeavors.",
    "Never stop asking questions and seeking understanding deeply.",
    "The more you learn, the more you realize how much you don't know.",
    "Intellectual humility is a sign of wisdom, not weakness in life.",
    "Admit when you don't know something and learn about it willingly.",
    "Not knowing is the first step to knowing something new entirely.",
    "Embrace being a beginner and the discomfort that comes with it.",
    "Beginners mind is open and ready to receive new information freely.",
    "Expert mind can be closed and resistant to new information sometimes.",
    "Cultivate beginners mind even as you gain expertise in your field.",
    "There is always more to learn, no one knows everything completely.",
    "Stay humble in your pursuit of knowledge and understanding.",
    "Humility attracts wisdom while pride repels it effectively.",
    "Pride comes before a fall in learning and in life generally.",
    "Stay teachable and coachable throughout your entire life journey.",
    "Feedback is a gift that helps you improve and grow faster.",
    "Seek feedback actively and receive it with grace and gratitude.",
    "Don't be defensive when receiving constructive criticism from others.",
    "Consider feedback carefully before deciding whether to act on it.",
    "Not all feedback is equally valuable, learn to discern wisely.",
    "Take what serves you and leave what doesn't from feedback given.",
    "You are the curator of your own growth and development journey.",
    "Take full ownership of your learning and personal growth consistently.",
    "No one is coming to save you, take responsibility for your life.",
    "You are the protagonist of your own story and journey in life.",
    "Write the story you want to live, starting from today forward.",
    "You have the pen, write your own destiny deliberately and boldly.",
    "Your life is your message to the world, make it meaningful.",
    "What do you want your life to stand for and represent deeply?",
    "Legacy is not about fame, it's about the impact you make on others.",
    "How do you want to be remembered by those who know you?",
    "Live in a way that honors your values and principles daily.",
    "Align your actions with your values for authentic living always.",
    "Congruence between words and actions builds trust and respect.",
    "Walk your talk and be consistent in what you say and do.",
    "Integrity is choosing courage over comfort in difficult moments.",
    "Choose what is right over what is easy, fast or convenient.",
    "The right path is often the harder path in life initially.",
    "Short term pleasure often comes at the cost of long term pain.",
    "Delayed gratification leads to greater rewards in the future.",
    "Temptation is everywhere, discipline is a daily choice and battle.",
    "Willpower is like a muscle that gets stronger with regular use.",
    "Strengthen your willpower muscle through consistent small challenges.",
    "Discipline is choosing what you want most over what you want now in each moment.",
    "This quote captures the essence of self mastery perfectly indeed.",
    "Mastery of self is the highest form of mastery to achieve.",
    "Conquer yourself before trying to conquer the world outside.",
    "The battlefield is within you, win the internal battles first always.",
    "Inner peace comes from winning the war within yourself completely.",
    "External achievements mean little without internal peace and harmony.",
    "True success includes peace of mind and fulfillment within.",
    "Wealth without health and happiness is meaningless ultimately.",
    "Health is the real wealth that money cannot buy or replace.",
    "Without health, all other achievements lose their meaning and luster.",
    "Take care of your body, it's the only place you have to live.",
    "Your body is a temple, treat it with respect and care always.",
    "Nourish your body with good food, exercise and adequate rest daily.",
    "Hydration is key to good health, drink plenty of water every day.",
    "Water is life, drink at least eight glasses every single day.",
    "Limit processed foods and sugar for better health outcomes overall.",
    "Whole foods provide the nutrients your body truly needs to thrive.",
    "Eat the rainbow of colorful fruits and vegetables for optimal nutrition.",
    "Variety in diet ensures you get a wide range of essential nutrients.",
    "Everything in moderation, including moderation itself sometimes.",
    "Balance is the key to sustainable healthy habits for life.",
    "Extreme diets are rarely sustainable in the long term at all.",
    "Small consistent changes lead to lasting transformation over time.",
    "Crash diets fail because they are not sustainable or healthy long term.",
    "Build habits that you can maintain for the rest of your life.",
    "Your future self will thank you for the healthy choices you make today.",
    "Invest in your health now to enjoy a better quality of life later.",
    "Prevention is better and cheaper than cure in healthcare always.",
    "Regular checkups can catch problems early when they are treatable.",
    "Listen to your body, it tells you when something is wrong.",
    "Pain is your body's way of signaling that attention is needed urgently.",
    "Don't ignore persistent symptoms, consult a healthcare professional promptly.",
    "Mental health is just as important as physical health in life.",
    "It's okay to not be okay sometimes, seek help when needed.",
    "Therapy is a sign of strength, not weakness in handling life.",
    "Talk to someone you trust when you are struggling emotionally.",
    "You don't have to face everything alone in this whole world.",
    "Asking for help is a sign of courage and self awareness always.",
    "We all need support sometimes, that's part of being human.",
    "Vulnerability is not weakness, it's emotional courage in action.",
    "Brené Brown's research on vulnerability changed my perspective completely.",
    "Daring greatly means showing up and being seen even when uncertain.",
    "Courage starts with showing up and letting yourself be seen truly.",
    "You cannot numb difficult emotions without numbing joy as well.",
    "Allow yourself to feel all emotions fully without judgment or resistance.",
    "Emotions are not good or bad, they are simply information to process.",
    "Process your emotions rather than suppressing or avoiding them entirely.",
    "Suppressed emotions don't disappear, they manifest in other ways eventually.",
    "Healthy emotional expression is key to psychological well being in life.",
    "Crying is a healthy way to release emotional tension and pain.",
    "Tears are not a sign of weakness, they are a release valve for emotions.",
    "It's okay to be vulnerable and show your true feelings authentically.",
    "Authenticity attracts genuine connections and meaningful relationships in life.",
    "Be real with people, pretense is exhausting and unsustainable always.",
    "Your authentic self is your best self, let that shine brightly.",
    "The world needs your unique gifts and perspectives expressed fully.",
    "Don't hide your light to make others comfortable in your presence.",
    "Shine brightly and inspire others to do the same in their lives.",
    "Your contribution matters more than you will ever know in life.",
    "The ripples of your actions extend far beyond what you can see.",
    "You impact the world simply by existing and being who you are.",
    "Make your impact a positive one through conscious choices daily.",
    "Be the change you wish to see in the world around you.",
    "Gandhi's words still resonate deeply with truth and wisdom today.",
    "Change starts with one person taking action and inspiring others.",
    "You have the power to make a difference starting right now today.",
    "Don't underestimate the power of one person's determined actions ever.",
    "History is shaped by individuals who refused to stay silent and passive.",
    "Your voice matters, use it to speak up for what is right always.",
    "Stand up for justice and equality wherever you see injustice happening.",
    "Silence in the face of injustice is complicity with the oppressor.",
    "Speak truth to power even when your voice shakes with fear.",
    "Courage is not the absence of fear, it's speaking up despite it.",
    "Future generations will judge us by our actions and our silence.",
    "Be on the right side of history in the choices you make today.",
    "Every vote matters in shaping the future of your community and nation.",
    "Participate actively in civic life and democratic processes available to you.",
    "Democracy requires active participation from informed citizens to function properly.",
    "Stay informed about issues that affect your life and community deeply.",
    "Critical thinking is essential for making informed decisions in life.",
    "Question information sources and verify facts before accepting them as truth.",
    "Media literacy is a crucial skill in the modern information age entirely.",
    "Algorithms shape what we see online, be aware of filter bubbles affecting you.",
    "Seek out diverse perspectives to broaden your understanding of the world.",
    "Echo chambers reinforce existing beliefs without challenging them constructively.",
    "Growth comes from engaging with ideas different from your own respectfully.",
    "Disagreement does not have to be disrespectful or hostile in nature.",
    "Disagree without being disagreeable in conversations and discussions always.",
    "Listen to understand, not just to respond or win arguments with others.",
    "Seek first to understand, then to be understood in conversations fully.",
    "Stephen Covey's principle applies to all relationships in life effectively.",
    "Empathetic listening builds trust and deepens connections between people.",
    "Most people don't listen with the intent to understand, they listen to reply.",
    "Be the exception who listens deeply and truly hears what others say.",
    "People feel valued when they are genuinely heard and understood deeply.",
    "Validation does not mean agreement, it means acknowledging someone's experience.",
    "You can validate someone's feelings without agreeing with their perspective completely.",
    "Everyone deserves to have their feelings acknowledged and respected in life.",
    "Basic respect costs nothing and means everything in human interactions.",
    "Treat others the way you want to be treated, the golden rule of life.",
    "Reciprocity is a fundamental principle of healthy relationships and societies.",
    "What goes around comes around in life eventually, good or bad.",
    "Karma is cause and effect applied to human actions and choices.",
    "Plant good seeds and you will reap a good harvest in time.",
    "Your actions today create the conditions for your future experiences entirely.",
    "Take responsibility for the energy and impact you bring into the world.",
    "Be mindful of your words because they have power to heal or harm.",
    "Words can build up or tear down, choose them wisely and carefully.",
    "Speak with kindness and intention in every conversation you have always.",
    "Your words create your reality to a significant extent in life.",
    "Affirmations rewired my brain for positivity and self belief over time.",
    "Speak positively about yourself and your life consistently every day.",
    "The words you say to yourself matter most of all in your life.",
    "Be your own biggest fan and supporter in your internal dialogue always.",
    "Self talk shapes your self image and confidence in powerful ways.",
    "Replace negative self talk with empowering and loving affirmations daily.",
    "You are worthy of love, success, happiness and abundance in life.",
    "Repeat that to yourself until you truly believe it deeply within.",
    "Affirmations work best when they feel true and believable to you personally.",
    "Start with affirmations that are a stretch but still possible to believe.",
    "Gradually increase the boldness of your affirmations over time consistently.",
    "Your beliefs expand as you prove to yourself what is possible in life.",
    "Evidence builds belief through consistent action and observed results.",
    "Take action that proves to yourself you are capable and strong enough.",
    "Nothing builds confidence like keeping promises you made to yourself reliably.",
    "Trust yourself by following through on your commitments consistently always.",
    "Self trust is the foundation of all confidence and self esteem in life.",
    "Build self trust through small daily acts of integrity with yourself.",
    "When you say you will do something, do it without exception always.",
    "Reliability starts with being reliable to yourself first and foremost.",
    "You can't pour from an empty cup, take care of yourself first always.",
    "Self care is not selfish, it is necessary maintenance for your well being.",
    "Put your oxygen mask on first before helping others in emergencies.",
    "You serve others best when you are at your best self genuinely.",
    "Taking care of yourself enables you to help others more effectively.",
    "You cannot give what you don't have within yourself to give others.",
    "Fill your own cup first so it overflows to others naturally.",
    "Self love is the foundation for loving others healthily and genuinely.",
    "You teach others how to treat you by how you treat yourself.",
    "Set boundaries that protect your peace and well being in life.",
    "Boundaries are not walls, they are gates that you control access through wisely.",
    "Healthy boundaries are essential for healthy relationships in life always.",
    "Learn to say no without guilt when something doesn't serve you well.",
    "No is a complete sentence and sometimes the kindest answer to give.",
    "Saying no to others is saying yes to yourself and your priorities.",
    "Your time and energy are precious resources, guard them carefully and wisely.",
    "Not everyone deserves access to you and your valuable time in life.",
    "Be selective about who you let into your inner circle and life.",
    "Quality over quantity applies to relationships as well as possessions.",
    "A few genuine friends are worth more than many superficial acquaintances.",
    "Deep connections with a few people beat shallow connections with many.",
    "Invest time and energy in relationships that are reciprocal and nourishing.",
    "Relationships require effort and intentionality from both parties to thrive.",
    "Friendship is a two way street that requires mutual care and effort.",
    "Reach out to friends regularly, don't wait for them to always come to you.",
    "Be the friend you wish to have in your own life consistently.",
    "Initiate plans, check in on people, show up for important moments always.",
    "Little gestures of kindness strengthen bonds more than grand gestures rarely.",
    "Consistency in small acts of care builds lasting trust and connection.",
    "Remember important dates and details about people's lives meaningfully.",
    "Pay attention to what matters to the people you care about deeply.",
    "Thoughtfulness is a language of love that everyone appreciates receiving.",
    "A simple message asking how someone is can make their entire day better.",
    "You never know who needs to hear from you today in this moment.",
    "That person you're thinking of might need your message right now today.",
    "Don't wait for a special occasion to reach out to loved ones.",
    "Every day is a good day to tell someone you appreciate them truly.",
    "Express gratitude to the people in your life regularly and genuinely.",
    "Tell people you love them while they are still here to hear it.",
    "Regret of not saying something is harder to bear than saying it.",
    "Better to have said it than to wonder what if forever after.",
    "Be bold in expressing love and appreciation to those you cherish deeply.",
    "Life is unpredictable, don't leave important words unsaid until tomorrow.",
    "If not now, when? The time to act is always present in life.",
    "Procrastination robs you of precious time and opportunities in life.",
    "Don't put off for tomorrow what you can do today meaningfully.",
    "The present moment is the only moment you truly have control over.",
    "Use your time wisely because it is your most non renewable resource.",
    "Time is the one thing you can never get back once it's gone.",
    "Make every moment count by being fully present and intentional always.",
    "Quality of attention is the greatest gift you can give to someone else.",
    "Be where your feet are, fully present in the here and now moment.",
    "Multitasking divides attention, presence requires single focused awareness entirely.",
    "Put your phone away when having conversations with people in person.",
    "Eye contact and active listening show respect and genuine interest always.",
    "Undivided attention is rare and precious in our distracted modern world.",
    "Be the person who makes others feel seen, heard and valued deeply.",
    "That is one of the greatest gifts you can give to another human being.",
    "Everyone craves genuine connection and understanding from others in life.",
    "Connection is the opposite of addiction according to research on the topic.",
    "We are wired for connection as human beings fundamentally and deeply.",
    "Loneliness is an epidemic in modern society with serious health consequences.",
    "Reach out to someone who might be lonely today and make a difference.",
    "Your simple hello could be the highlight of someone's entire day today.",
    "Kindness ripples outward in ways you will never fully know or understand.",
    "The effects of your kindness extend far beyond what you can perceive now.",
    "Trust that every act of kindness makes the world a little bit better.",
    "You are making a difference just by choosing to be kind today.",
    "Keep being the wonderful person that you are in this world always.",
    "The world needs more people like you who care and show up daily.",
    "Your presence in this group makes it better for everyone involved truly.",
    "Thanks for being part of this amazing community and contributing positively.",
    "Together we are building something special and meaningful in this space.",
    "This group is what it is because of members like you actively participating.",
    "Every member adds unique value to our community discussions and interactions.",
    "Let's continue to make this the best group on Telegram together always.",
    "Keep the conversations going and the connections growing every single day.",
    "We appreciate each and every one of you being here with us today.",
    "Thank you for being awesome and making this community so vibrant and alive!",
]

# Combine: 25% praise + 75% general
MESSAGES = praise_msgs + general_msgs

# Pad with more general messages to hit 1000+
while len(MESSAGES) < 1000:
    MESSAGES.append(f"Keep the conversation going in this amazing group! Day {len(MESSAGES) + 1} of being active here!")

print(f"✅ Total unique messages loaded: {len(MESSAGES)}")
print(f"✅ Praise messages (Carnival Chat tareef): {len(praise_msgs)} ({len(praise_msgs)/len(MESSAGES)*100:.1f}%)")
print(f"✅ General messages: {len(general_msgs)} ({len(general_msgs)/len(MESSAGES)*100:.1f}%)")

# --- SETTINGS ---
SEND_INTERVAL = 6  # Har 6 second mein 1 message

# --- MAIN LOGIC ---
async def main():
    client = TelegramClient(SESSION_NAME, API_ID, API_HASH)

    try:
        await client.start(phone=PHONE_NUMBER)
        print("✅ Successfully logged in to Telegram!")

        # Target group resolve karo
        try:
            entity = await client.get_entity(TARGET_GROUP)
            group_name = entity.title if hasattr(entity, 'title') else TARGET_GROUP
            print(f"✅ Connected to group: {group_name}")
        except Exception as e:
            print(f"❌ Failed to find/get group: {e}")
            print("💡 Make sure you are a member of this group!")
            return

        message_index = 0
        total_sent = 0

        print(f"🚀 Starting auto-messenger...")
        print(f"⏱️  Sending 1 message every 6 seconds")
        print(f"💬 Total messages in pool: {len(MESSAGES)}")
        print("=" * 50)

        while True:
            # Reset index if all messages sent
            if message_index >= len(MESSAGES):
                message_index = 0
                print("🔄 All messages used once. Restarting from beginning...")

            current_message = MESSAGES[message_index]

            try:
                await client.send_message(entity, current_message)
                total_sent += 1
                print(f"✅ [#{total_sent}] Sent: {current_message[:70]}...")
                message_index += 1

                # Wait 6 seconds before next message
                await asyncio.sleep(6)

            except errors.FloodWaitError as e:
                wait_seconds = e.seconds
                print(f"⚠️ Flood wait: {wait_seconds}s ({wait_seconds/60:.1f} min)...")
                await asyncio.sleep(wait_seconds + 5)

            except errors.RPCError as e:
                print(f"❌ Telegram API error: {e}")
                await asyncio.sleep(30)

            except Exception as e:
                print(f"❌ Error: {e}")
                await asyncio.sleep(10)

    except Exception as e:
        print(f"❌ Fatal error: {e}")
    finally:
        await client.disconnect()
        print("🔌 Disconnected from Telegram.")

# --- RUN THE SCRIPT ---
if __name__ == "__main__":
    asyncio.run(main())